Repository finopsfoundation/framework, pull requests merged in 2022-05, with the labels that each got.

#548 Significant content update for "Cloud Policy & Governance" Capability page - all areas populated
  _capabilities/policy-governance.md
Labels: f2-framework, framework-capability, f2 team

#562 Bdm education enablement update
  _capabilities/education-enablement.md
Labels: f2-framework, framework-capability, Community help: WANTED!, Contribution

#574 [framework ] updates for framework and projects content
  _capabilities/education-enablement.md
  _capabilities/policy-governance.md
  _data/navigation_side.yml
  _resources/project--adopting-finops-avoiding-pitfalls.md
  _resources/project--adopting-finops.md
  img/adopting-finops/adopting-finops-avoiding-pitfalls-image1-20220517.png
Labels: documentation, enhancement, f2-framework, framework-capability, framework-story, f2 team

#579 [partner certification] updating profile page to add FCP certification status
  _tools-services/finout.md
Labels: general member, f2 team, vendor, certification

#580 [partner members] update finout partner profile to reflect number of FOCP certifiied employees
  _tools-services/finout.md
Labels: general member, f2 team, vendor
