Repository finopsfoundation/framework, pull requests merged in 2022-09, with the labels that each got.

#683 General typo & tidy-up of playbook content
  _resources/project--finops-assessment.md
Labels: documentation, f2-framework, framework-playbook

#690 [partner member] fairwinds profile page updated to reflect FCS certification
  _tools-services/fairwinds.md
Labels: general member, partner, certification

#692 [framework] capability metadata updates to improve search
  _capabilities/analysis-showback.md
  _capabilities/asset-management.md
  _capabilities/budget-management.md
  _capabilities/chargeback.md
  _capabilities/cost-allocation.md
  _capabilities/data-normalization.md
  _capabilities/decision-accountability-structure.md
  _capabilities/education-enablement.md
  _capabilities/establish-finops-culture.md
  _capabilities/forecasting.md
  _capabilities/manage-anomalies.md
  _capabilities/manage-commitment-based-discounts.md
  _capabilities/manage-shared-cloud-costs.md
  _capabilities/measure-unit-costs.md
  _capabilities/onboarding-workloads.md
  _capabilities/policy-governance.md
  _capabilities/utilization-efficiency.md
  _capabilities/workload-management-automation.md
Labels: enhancement, f2-framework, framework-capability, f2 team

#693 [framework] capability resource and content updates
  _capabilities/analysis-showback.md
  _capabilities/asset-management.md
  _capabilities/budget-management.md
  _capabilities/chargeback.md
  _capabilities/cost-allocation.md
  _capabilities/data-normalization.md
  _capabilities/decision-accountability-structure.md
  _capabilities/education-enablement.md
  _capabilities/establish-finops-culture.md
  _capabilities/forecasting.md
  _capabilities/manage-anomalies.md
  _capabilities/manage-commitment-based-discounts.md
  _capabilities/manage-shared-cloud-costs.md
  _capabilities/measure-unit-costs.md
  _capabilities/onboarding-workloads.md
  _capabilities/policy-governance.md
  _capabilities/utilization-efficiency.md
  _capabilities/workload-management-automation.md
  _resources/story--ri-purchasing.md
Labels: enhancement, f2-framework, framework-capability, framework-story, f2 team

#695 [framework] capability content updates
  _resources/project--sustainability.md
Labels: enhancement, f2-framework, framework-capability, framework-resource, f2 team
