Repository finopsfoundation/framework, pull requests merged in 2022-03, with the labels that each got.

#518 [framework] update for framework capability content
  _capabilities/asset-management.md
Labels: enhancement, f2-framework, framework-capability, Contribution

#514 Update maturity assessment info
  _capabilities/establish-finops-culture.md
Labels: Contribution

#522 update to partner member platform and solution certification requirement language
  _pages/members/finops-certified-platform.html
  _pages/members/vendor-certification.md
Labels: documentation, enhancement, f2 team, vendor
