Repository finopsfoundation/framework, pull requests merged in 2022-11, with the labels that each got.

#729 [framework ] updates for framework capability content
  _capabilities/decision-accountability-structure.md
Labels: enhancement, f2-framework, framework-capability, f2 team

#735 content updates
  _capabilities/asset-management.md
  _capabilities/chargeback.md
  _pages/resources/terminology.md
  _resources/project--finops-tbm.md
Labels: enhancement, f2-framework, framework-capability, framework-resource, f2 team

#736 added new terms to the terminology page
  _pages/resources/terminology.md
Labels: enhancement, f2 team, Contribution

#741 adding framework whats_new page
  _data/navigation_side.yml
  _pages/framework/whats-new.md
  _resources/project--accurate-cloud-forecasts.md
  _resources/project--container-cost-allocation.md
  _resources/project--container-costs.md
  _resources/project--forecasting-playbook.md
  _resources/project--sustainability.md
  _resources/story--anomaly-detection-basics.md
  _resources/story--anomaly-detection-navigating-infrastructure-changes.md
Labels: enhancement, framework-capability, framework-resource, f2 team

#745 layout updates
  _pages/framework/whats-new.md
Labels: enhancement, f2-framework, f2 team

#748 updated partner certification badge image files
  img/certs/finops-certified-platform.png
  img/certs/finops-certified-service-provider.png
  img/certs/finops-certified-solution.png
  img/certs/finops-certified-training-partner.png
Labels: documentation, enhancement, partner, certification

#750 added FCP certification label to Harness; plus 1 fix
  _pages/framework/whats-new.md
  _tools-services/harness.md
Labels: bug/typo, documentation, general member, f2 team, partner

#756 Integration of gathered knowledge to update Forecasting capability
  _capabilities/forecasting.md
Labels: documentation, enhancement, f2-framework, change request, framework-capability, f2 team

#759 Incorporate unit economics playbook content into capability
  _capabilities/measure-unit-costs.md
  _pages/introduction/what-is-finops.md
Labels: enhancement, f2-framework, framework-capability, f2 team
